name: 'dbt_snowflake_materialize'
version: '1.0.0'
config-version: 2

profile: 'default'

analysis-paths: ["analyses"]
macro-paths: ["macros"]
model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
